# Generated by Django 5.0.1 on 2024-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0004_user21'),
    ]

    operations = [
        migrations.CreateModel(
            name='User22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('reason', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('blood_volume', models.IntegerField()),
            ],
            options={
                'db_table': 'User22',
            },
        ),
    ]
