# Generated by Django 5.0.1 on 2024-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0007_user24'),
    ]

    operations = [
        migrations.CreateModel(
            name='User25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group1', models.IntegerField()),
                ('blood_group2', models.IntegerField()),
            ],
            options={
                'db_table': 'User25',
            },
        ),
    ]
