# Generated by Django 5.0.1 on 2024-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0008_user25'),
    ]

    operations = [
        migrations.CreateModel(
            name='User26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group1', models.IntegerField()),
                ('blood_group2', models.IntegerField()),
            ],
            options={
                'db_table': 'User26',
            },
        ),
    ]
