# Generated by Django 5.0.1 on 2024-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0009_user26'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User26',
        ),
    ]
