# Generated by Django 5.0.1 on 2024-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0012_user27_delete_user25_delete_user26'),
    ]

    operations = [
        migrations.CreateModel(
            name='User28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group1', models.IntegerField()),
                ('blood_group2', models.IntegerField()),
            ],
            options={
                'db_table': 'User28',
            },
        ),
        migrations.CreateModel(
            name='User29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=50)),
                ('blood', models.IntegerField()),
            ],
            options={
                'db_table': 'User29',
            },
        ),
        migrations.DeleteModel(
            name='User27',
        ),
    ]
