# Generated by Django 5.0.1 on 2024-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0014_user30'),
    ]

    operations = [
        migrations.CreateModel(
            name='User31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=50)),
                ('blood_volume', models.IntegerField()),
            ],
            options={
                'db_table': 'User31',
            },
        ),
    ]
