# Generated by Django 5.0.1 on 2024-03-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0018_user30'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User30',
        ),
    ]
