# Generated by Django 5.0.1 on 2024-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0020_user30'),
    ]

    operations = [
        migrations.CreateModel(
            name='User33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_groupA1', models.IntegerField()),
                ('blood_groupB1', models.IntegerField()),
                ('blood_groupO1', models.IntegerField()),
                ('blood_groupAB1', models.IntegerField()),
                ('blood_groupA2', models.IntegerField()),
                ('blood_groupB2', models.IntegerField()),
                ('blood_groupO2', models.IntegerField()),
                ('blood_groupAB2', models.IntegerField()),
            ],
            options={
                'db_table': 'User33',
            },
        ),
    ]
