# Generated by Django 5.0.1 on 2024-03-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0022_user34'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User22',
        ),
    ]
