# Generated by Django 5.0.1 on 2024-03-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0023_delete_user22'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User30',
        ),
    ]
