# Generated by Django 5.0.1 on 2024-03-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0025_user30'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User33',
        ),
    ]
